baseurl: "https://fcofdez.github.io"
languageCode: "en-us"
title: "Francisco Fernandez's blog"
theme: "xmin-light"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Francisco Fernandez's blog
      url: ""
      weight: 1
    - name: Subscribe
      url: "index.xml"

params:
  description: "Francisco Fernandez's blog"
  footer: "[Francisco Fernandez](https://fcofdez.github.io) 2021 | [Github](https://github.com/fcofdez) | [Twitter](https://twitter.com/fcofdezc)"
